name: plenimind_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.5.10
  permission_handler: ^12.0.1
  http: ^1.4.0
  async: ^2.12.0
  provider: ^6.1.5+1
  awesome_dialog: ^3.1.0
  cupertino_icons: ^1.0.0
  flutter_animate: ^4.0.0
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  logging: ^1.3.0
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
